const SONNET_PATTERNS = [
  // Greetings (user starting a session, needs smart response)
  /^hi$/i,
  /^hey$/i,
  /^hello$/i,
  /^yo$/i,
  /^sup$/i,
  /^what'?s up/i,
  /^good (morning|afternoon|evening)/i,
  /^gm$/i,

  // Recommendations & session management
  /what should i do/i,
  /what.*today/i,
  /recommend/i,
  /suggest/i,
  /what else/i,
  /what.*next/i,
  /can you.*suggest/i,
  /start.*session/i,
  /new.*session/i,
  /want to do/i,
  /i want to/i,
  /make.*plan/i,
  /create.*session/i,
  /swap/i,
  /instead of/i,
  /change.*to/i,
  /skip/i,

  // Knowledge & form questions
  /how.*do.*i/i,
  /how.*should/i,
  /how.*many/i,
  /how.*much/i,
  /how.*heavy/i,
  /how.*long/i,
  /how.*often/i,
  /what.*muscles/i,
  /what.*is.*the.*best/i,
  /what.*are.*the.*best/i,
  /is.*my.*form/i,
  /form.*check/i,
  /proper.*form/i,
  /technique/i,
  /tell.*me.*about/i,
  /explain/i,
  /why.*should/i,
  /difference.*between/i,
  /alternative/i,
  /substitute/i,
  /replace/i,

  // Goals & programming
  /goal/i,
  /progress/i,
  /personal.*best/i,
  /pb/i,
  /pr/i,
  /history.*for/i,
  /how.*am.*i.*doing/i,
  /posture/i,
  /improve/i,
  /fix/i,
  /set.*goal/i,
  /plan/i,
  /program/i,
  /advice/i,
  /help.*with/i,
  /what.*work/i,
  /should i/i,

  // Backfill / past dates
  /\d{1,2}(st|nd|rd|th)?\s*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)/i,
  /\d{1,2}(st|nd|rd|th)?\s+(january|february|march|april|may|june|july|august|september|october|november|december)/i,
  /(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\s*\d{1,2}/i,
  /yesterday/i,
  /last\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)/i,
  /\d{1,2}\/\d{1,2}/,

  // Recovery & injury
  /sore/i,
  /pain/i,
  /injur/i,
  /recover/i,
  /rest/i,
  /warm.*up/i,
  /cool.*down/i,
  /stretch/i,
];

export function routeIntent(message: string): "haiku" | "sonnet" {
  if (SONNET_PATTERNS.some((p) => p.test(message))) return "sonnet";
  return "haiku";
}
